export const RANDOM_PRODUCTS: string[] = [
  // Absurd / funny
  "A sentient toaster that critiques your breakfast choices",
  "Uber but for therapists",
  "An app that tells you if your outfit is ugly",
  "A $400 water bottle with a built-in hydration AI",
  "LinkedIn for dogs",
  "A browser extension that auto-negotiates your salary",
  "A startup that replaces your morning standup with an AI",
  "An app that roasts your resume before you submit it",
  "A subscription service for clean socks delivered daily",
  "AI-generated bedtime stories personalized to your child",
  "A dating app but the AI ghosts you first to build resilience",
  "A wellness app that tells you to go outside instead of using it",
  "An alarm clock that charges you $1 every time you snooze",
  "A mirror that gives you honest feedback before you leave the house",
  "Spotify but it only plays music your enemies would hate",
  "A Chrome extension that replaces all ads with pictures of your dog",
  "An app that writes passive-aggressive Slack messages so you don't have to",
  "A fridge that locks itself after 10 PM",
  "GPS navigation but narrated by a disappointed parent",
  "A to-do list app that deletes tasks you've been avoiding for over 30 days",

  // Plausible / real startup energy
  "AI-powered contract review for freelancers",
  "A carbon footprint tracker embedded in your credit card",
  "On-demand meal prep delivery for athletes",
  "Mental health journaling app with AI pattern detection",
  "B2B SaaS for automating vendor invoice reconciliation",
  "A platform that turns Notion docs into onboarding flows",
  "An AI that schedules your entire week from a single voice memo",
  "Peer-to-peer lending marketplace for small creative projects",
  "A tool that turns customer support tickets into product roadmap insights",
  "Background check infrastructure for the gig economy",

  // Deep tech / moonshot
  "A wearable that detects stress before you feel it",
  "Personalized nutrition using continuous glucose monitoring data",
  "AI that predicts employee churn 90 days in advance",
  "Real-time language translation earbuds for business meetings",
  "A drone delivery network for rural pharmacies",
  "Brain-computer interface for hands-free laptop control",
  "AI-powered legal aid for people who can't afford lawyers",
  "Satellite internet for livestock health monitoring on remote farms",
  "Carbon capture credits marketplace for small businesses",
  "Robotic last-mile delivery for dense urban apartment buildings",

  // Consumer / social
  "A social network where you can only post once a week",
  "An app that finds the exact song stuck in your head",
  "Neighborhood skill-sharing marketplace (teach yoga, learn plumbing)",
  "A travel app that plans your entire trip from a single budget number",
  "Split-payment app for group vacations that actually works",
  "Anonymous peer accountability groups for building habits",
  "A book club app with AI-powered discussion questions",
  "Hyper-local news aggregator built on citizen journalism",
  "A platform for renting out your parking spot by the hour",
  "An app that finds free outdoor movie screenings near you",
];
